### PR TITLE
Fix Password Reset Redirects

### LINKED ISSUE #400: Redirect to user dashboard if no login session after a successfull password reset
Discussion: https://github.com/orgs/fief-dev/discussions/392

### PR DESCRIPTION
**Pull request by ApprenticeofEnder**
Fixes #400.

Summary of changes:
- Updated devcontainer image to allow Codespaces to work
- Added redirect to Auth Dashboard Profile (which forces a redirect to the login page) after a password reset without a session
- Modified corresponding integration test
- Fixed pytest dependency shenanigans that caused *literally the entire test suite to break somehow*

NOTE: `pytest-asyncio==0.21.1` caused an error that resulted in `AttributeError: 'FixtureDef' object has no attribute 'unittest'`. According to [the associated Github Issue](https://github.com/pytest-dev/pytest/issues/12269), bumping to 0.21.2 (and, subsequently, pinning the `pytest` and `pytest-cov` versions) fixed the issue.

### CODE REVIEW

**Comment by frankie567** [comment]
Thank you for this! Looks good 👍 

I've fixed the pytest dependencies on the main branch; could you rebase your PR without the changes on `pyproject.toml`?

**Comment by ApprenticeofEnder** [comment]
That should work the same way, I wasn't able to figure out how to rebase it in a way that would selectively keep changes.

**Comment by frankie567** [comment]
That'll do the trick :) For the record, you can achieve that using `[git rebase`](https://git-scm.com/docs/git-rebase).

@all-contributors add @ApprenticeofEnder for code

**Comment by ApprenticeofEnder** [comment]
> That'll do the trick :) For the record, you can achieve that using [`git rebase`](https://git-scm.com/docs/git-rebase).
> 
> @all-contributors add @ApprenticeofEnder for code

I did actually try that, but I think I messed something up and I couldn't actually rebase to the point I wanted to. I'll have to give it another try later.

**Pull request merged**
